"""add new relationship2

Revision ID: 36f393116d0d
Revises: 0e488ae190b2
Create Date: 2023-08-13 17:21:04.462198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36f393116d0d'
down_revision: Union[str, None] = '0e488ae190b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subjects', sa.Column('group_id', sa.Integer(), nullable=True))
    op.drop_constraint('subjects_grade_id_fkey', 'subjects', type_='foreignkey')
    op.create_foreign_key(None, 'subjects', 'groups', ['group_id'], ['id'])
    op.drop_column('subjects', 'grade_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subjects', sa.Column('grade_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'subjects', type_='foreignkey')
    op.create_foreign_key('subjects_grade_id_fkey', 'subjects', 'grades', ['grade_id'], ['id'])
    op.drop_column('subjects', 'group_id')
    # ### end Alembic commands ###
